# Generated by Django 3.2.7 on 2021-09-21 06:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a project framework/technology used (e.g. Django)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic', models.FilePathField(path='/img')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.author')),
                ('technologies', models.ManyToManyField(help_text='Select framework/technologies used for the project', to='project.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('location_url', models.CharField(max_length=150)),
                ('summary', models.TextField(help_text='Enter a brief description of the repository', max_length=1000)),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Too poor'), (2, 'Poor'), (3, 'Try'), (4, 'Somewhat good'), (5, 'Neutral'), (6, 'Somewhat good'), (7, 'Good'), (8, 'Too good'), (9, 'Near perfect'), (10, 'Excellent')], default='5', help_text='Project Ratings(Out of 10)', max_length=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.image')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.project')),
            ],
            options={
                'ordering': ['deployment_date'],
            },
        ),
    ]
