# Generated by Django 3.2.7 on 2021-09-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_detail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pic',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.image'),
        ),
    ]
