# Generated by Django 3.2.7 on 2021-09-21 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.FilePathField(default=django.utils.timezone.now, path='/images'),
            preserve_default=False,
        ),
    ]
