# Generated by Django 3.2.7 on 2021-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
