# Generated by Django 3.2.7 on 2021-09-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20210921_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.detail'),
        ),
    ]
